import embedIconsCodepenPngUrl from '@tldraw/assets/embed-icons/codepen.png?url'
import embedIconsCodesandboxPngUrl from '@tldraw/assets/embed-icons/codesandbox.png?url'
import embedIconsDesmosPngUrl from '@tldraw/assets/embed-icons/desmos.png?url'
import embedIconsExcalidrawPngUrl from '@tldraw/assets/embed-icons/excalidraw.png?url'
import embedIconsFeltPngUrl from '@tldraw/assets/embed-icons/felt.png?url'
import embedIconsFigmaPngUrl from '@tldraw/assets/embed-icons/figma.png?url'
import embedIconsGithubGistPngUrl from '@tldraw/assets/embed-icons/github_gist.png?url'
import embedIconsGoogleCalendarPngUrl from '@tldraw/assets/embed-icons/google_calendar.png?url'
import embedIconsGoogleMapsPngUrl from '@tldraw/assets/embed-icons/google_maps.png?url'
import embedIconsGoogleSlidesPngUrl from '@tldraw/assets/embed-icons/google_slides.png?url'
import embedIconsObservablePngUrl from '@tldraw/assets/embed-icons/observable.png?url'
import embedIconsReplitPngUrl from '@tldraw/assets/embed-icons/replit.png?url'
import embedIconsScratchPngUrl from '@tldraw/assets/embed-icons/scratch.png?url'
import embedIconsSpotifyPngUrl from '@tldraw/assets/embed-icons/spotify.png?url'
import embedIconsTldrawPngUrl from '@tldraw/assets/embed-icons/tldraw.png?url'
import embedIconsValTownPngUrl from '@tldraw/assets/embed-icons/val_town.png?url'
import embedIconsVimeoPngUrl from '@tldraw/assets/embed-icons/vimeo.png?url'
import embedIconsYoutubePngUrl from '@tldraw/assets/embed-icons/youtube.png?url'
import fontsIBMPlexMonoMediumWoff2Url from '@tldraw/assets/fonts/IBMPlexMono-Medium.woff2?url'
import fontsIBMPlexSansMediumWoff2Url from '@tldraw/assets/fonts/IBMPlexSans-Medium.woff2?url'
import fontsIBMPlexSerifMediumWoff2Url from '@tldraw/assets/fonts/IBMPlexSerif-Medium.woff2?url'
import fontsShantellSansTldrawishWoff2Url from '@tldraw/assets/fonts/Shantell_Sans-Tldrawish.woff2?url'
import iconsIcon0MergedSvgUrl from '@tldraw/assets/icons/icon/0_merged.svg?url'
import translationsZhCnJsonUrl from '@tldraw/assets/translations/zh-cn.json?url'

export default {
    fonts: {
        monospace: fontsIBMPlexMonoMediumWoff2Url,
        sansSerif: fontsIBMPlexSansMediumWoff2Url,
        serif: fontsIBMPlexSerifMediumWoff2Url,
        draw: fontsShantellSansTldrawishWoff2Url,
    },
    icons: {
        'align-bottom': iconsIcon0MergedSvgUrl + '#align-bottom',
        'align-center-horizontal': iconsIcon0MergedSvgUrl + '#align-center-horizontal',
        'align-center-vertical': iconsIcon0MergedSvgUrl + '#align-center-vertical',
        'align-left': iconsIcon0MergedSvgUrl + '#align-left',
        'align-right': iconsIcon0MergedSvgUrl + '#align-right',
        'align-top': iconsIcon0MergedSvgUrl + '#align-top',
        'arrow-left': iconsIcon0MergedSvgUrl + '#arrow-left',
        'arrowhead-arrow': iconsIcon0MergedSvgUrl + '#arrowhead-arrow',
        'arrowhead-bar': iconsIcon0MergedSvgUrl + '#arrowhead-bar',
        'arrowhead-diamond': iconsIcon0MergedSvgUrl + '#arrowhead-diamond',
        'arrowhead-dot': iconsIcon0MergedSvgUrl + '#arrowhead-dot',
        'arrowhead-none': iconsIcon0MergedSvgUrl + '#arrowhead-none',
        'arrowhead-square': iconsIcon0MergedSvgUrl + '#arrowhead-square',
        'arrowhead-triangle-inverted': iconsIcon0MergedSvgUrl + '#arrowhead-triangle-inverted',
        'arrowhead-triangle': iconsIcon0MergedSvgUrl + '#arrowhead-triangle',
        blob: iconsIcon0MergedSvgUrl + '#blob',
        'bring-forward': iconsIcon0MergedSvgUrl + '#bring-forward',
        'bring-to-front': iconsIcon0MergedSvgUrl + '#bring-to-front',
        broken: iconsIcon0MergedSvgUrl + '#broken',
        'check-circle': iconsIcon0MergedSvgUrl + '#check-circle',
        check: iconsIcon0MergedSvgUrl + '#check',
        'chevron-down': iconsIcon0MergedSvgUrl + '#chevron-down',
        'chevron-left': iconsIcon0MergedSvgUrl + '#chevron-left',
        'chevron-right': iconsIcon0MergedSvgUrl + '#chevron-right',
        'chevron-up': iconsIcon0MergedSvgUrl + '#chevron-up',
        'chevrons-ne': iconsIcon0MergedSvgUrl + '#chevrons-ne',
        'chevrons-sw': iconsIcon0MergedSvgUrl + '#chevrons-sw',
        'clipboard-copied': iconsIcon0MergedSvgUrl + '#clipboard-copied',
        'clipboard-copy': iconsIcon0MergedSvgUrl + '#clipboard-copy',
        color: iconsIcon0MergedSvgUrl + '#color',
        'cross-2': iconsIcon0MergedSvgUrl + '#cross-2',
        'cross-circle': iconsIcon0MergedSvgUrl + '#cross-circle',
        'dash-dashed': iconsIcon0MergedSvgUrl + '#dash-dashed',
        'dash-dotted': iconsIcon0MergedSvgUrl + '#dash-dotted',
        'dash-draw': iconsIcon0MergedSvgUrl + '#dash-draw',
        'dash-solid': iconsIcon0MergedSvgUrl + '#dash-solid',
        disconnected: iconsIcon0MergedSvgUrl + '#disconnected',
        discord: iconsIcon0MergedSvgUrl + '#discord',
        'distribute-horizontal': iconsIcon0MergedSvgUrl + '#distribute-horizontal',
        'distribute-vertical': iconsIcon0MergedSvgUrl + '#distribute-vertical',
        dot: iconsIcon0MergedSvgUrl + '#dot',
        'dots-horizontal': iconsIcon0MergedSvgUrl + '#dots-horizontal',
        'dots-vertical': iconsIcon0MergedSvgUrl + '#dots-vertical',
        'drag-handle-dots': iconsIcon0MergedSvgUrl + '#drag-handle-dots',
        duplicate: iconsIcon0MergedSvgUrl + '#duplicate',
        edit: iconsIcon0MergedSvgUrl + '#edit',
        'external-link': iconsIcon0MergedSvgUrl + '#external-link',
        'fill-fill': iconsIcon0MergedSvgUrl + '#fill-fill',
        'fill-none': iconsIcon0MergedSvgUrl + '#fill-none',
        'fill-pattern': iconsIcon0MergedSvgUrl + '#fill-pattern',
        'fill-semi': iconsIcon0MergedSvgUrl + '#fill-semi',
        'fill-solid': iconsIcon0MergedSvgUrl + '#fill-solid',
        follow: iconsIcon0MergedSvgUrl + '#follow',
        following: iconsIcon0MergedSvgUrl + '#following',
        'font-draw': iconsIcon0MergedSvgUrl + '#font-draw',
        'font-mono': iconsIcon0MergedSvgUrl + '#font-mono',
        'font-sans': iconsIcon0MergedSvgUrl + '#font-sans',
        'font-serif': iconsIcon0MergedSvgUrl + '#font-serif',
        'geo-arrow-down': iconsIcon0MergedSvgUrl + '#geo-arrow-down',
        'geo-arrow-left': iconsIcon0MergedSvgUrl + '#geo-arrow-left',
        'geo-arrow-right': iconsIcon0MergedSvgUrl + '#geo-arrow-right',
        'geo-arrow-up': iconsIcon0MergedSvgUrl + '#geo-arrow-up',
        'geo-check-box': iconsIcon0MergedSvgUrl + '#geo-check-box',
        'geo-cloud': iconsIcon0MergedSvgUrl + '#geo-cloud',
        'geo-diamond': iconsIcon0MergedSvgUrl + '#geo-diamond',
        'geo-ellipse': iconsIcon0MergedSvgUrl + '#geo-ellipse',
        'geo-heart': iconsIcon0MergedSvgUrl + '#geo-heart',
        'geo-hexagon': iconsIcon0MergedSvgUrl + '#geo-hexagon',
        'geo-octagon': iconsIcon0MergedSvgUrl + '#geo-octagon',
        'geo-oval': iconsIcon0MergedSvgUrl + '#geo-oval',
        'geo-pentagon': iconsIcon0MergedSvgUrl + '#geo-pentagon',
        'geo-rectangle': iconsIcon0MergedSvgUrl + '#geo-rectangle',
        'geo-rhombus-2': iconsIcon0MergedSvgUrl + '#geo-rhombus-2',
        'geo-rhombus': iconsIcon0MergedSvgUrl + '#geo-rhombus',
        'geo-star': iconsIcon0MergedSvgUrl + '#geo-star',
        'geo-trapezoid': iconsIcon0MergedSvgUrl + '#geo-trapezoid',
        'geo-triangle': iconsIcon0MergedSvgUrl + '#geo-triangle',
        'geo-x-box': iconsIcon0MergedSvgUrl + '#geo-x-box',
        github: iconsIcon0MergedSvgUrl + '#github',
        group: iconsIcon0MergedSvgUrl + '#group',
        'horizontal-align-end': iconsIcon0MergedSvgUrl + '#horizontal-align-end',
        'horizontal-align-middle': iconsIcon0MergedSvgUrl + '#horizontal-align-middle',
        'horizontal-align-start': iconsIcon0MergedSvgUrl + '#horizontal-align-start',
        'info-circle': iconsIcon0MergedSvgUrl + '#info-circle',
        leading: iconsIcon0MergedSvgUrl + '#leading',
        link: iconsIcon0MergedSvgUrl + '#link',
        lock: iconsIcon0MergedSvgUrl + '#lock',
        menu: iconsIcon0MergedSvgUrl + '#menu',
        minus: iconsIcon0MergedSvgUrl + '#minus',
        mixed: iconsIcon0MergedSvgUrl + '#mixed',
        pack: iconsIcon0MergedSvgUrl + '#pack',
        plus: iconsIcon0MergedSvgUrl + '#plus',
        'question-mark-circle': iconsIcon0MergedSvgUrl + '#question-mark-circle',
        'question-mark': iconsIcon0MergedSvgUrl + '#question-mark',
        redo: iconsIcon0MergedSvgUrl + '#redo',
        'reset-zoom': iconsIcon0MergedSvgUrl + '#reset-zoom',
        'rotate-ccw': iconsIcon0MergedSvgUrl + '#rotate-ccw',
        'rotate-cw': iconsIcon0MergedSvgUrl + '#rotate-cw',
        'send-backward': iconsIcon0MergedSvgUrl + '#send-backward',
        'send-to-back': iconsIcon0MergedSvgUrl + '#send-to-back',
        'share-1': iconsIcon0MergedSvgUrl + '#share-1',
        'size-extra-large': iconsIcon0MergedSvgUrl + '#size-extra-large',
        'size-large': iconsIcon0MergedSvgUrl + '#size-large',
        'size-medium': iconsIcon0MergedSvgUrl + '#size-medium',
        'size-small': iconsIcon0MergedSvgUrl + '#size-small',
        'spline-cubic': iconsIcon0MergedSvgUrl + '#spline-cubic',
        'spline-line': iconsIcon0MergedSvgUrl + '#spline-line',
        'stack-horizontal': iconsIcon0MergedSvgUrl + '#stack-horizontal',
        'stack-vertical': iconsIcon0MergedSvgUrl + '#stack-vertical',
        'status-offline': iconsIcon0MergedSvgUrl + '#status-offline',
        'stretch-horizontal': iconsIcon0MergedSvgUrl + '#stretch-horizontal',
        'stretch-vertical': iconsIcon0MergedSvgUrl + '#stretch-vertical',
        'text-align-center': iconsIcon0MergedSvgUrl + '#text-align-center',
        'text-align-left': iconsIcon0MergedSvgUrl + '#text-align-left',
        'text-align-right': iconsIcon0MergedSvgUrl + '#text-align-right',
        'toggle-off': iconsIcon0MergedSvgUrl + '#toggle-off',
        'toggle-on': iconsIcon0MergedSvgUrl + '#toggle-on',
        'tool-arrow': iconsIcon0MergedSvgUrl + '#tool-arrow',
        'tool-eraser': iconsIcon0MergedSvgUrl + '#tool-eraser',
        'tool-frame': iconsIcon0MergedSvgUrl + '#tool-frame',
        'tool-hand': iconsIcon0MergedSvgUrl + '#tool-hand',
        'tool-highlight': iconsIcon0MergedSvgUrl + '#tool-highlight',
        'tool-laser': iconsIcon0MergedSvgUrl + '#tool-laser',
        'tool-line': iconsIcon0MergedSvgUrl + '#tool-line',
        'tool-media': iconsIcon0MergedSvgUrl + '#tool-media',
        'tool-note': iconsIcon0MergedSvgUrl + '#tool-note',
        'tool-pencil': iconsIcon0MergedSvgUrl + '#tool-pencil',
        'tool-pointer': iconsIcon0MergedSvgUrl + '#tool-pointer',
        'tool-screenshot': iconsIcon0MergedSvgUrl + '#tool-screenshot',
        'tool-text': iconsIcon0MergedSvgUrl + '#tool-text',
        trash: iconsIcon0MergedSvgUrl + '#trash',
        twitter: iconsIcon0MergedSvgUrl + '#twitter',
        undo: iconsIcon0MergedSvgUrl + '#undo',
        ungroup: iconsIcon0MergedSvgUrl + '#ungroup',
        unlock: iconsIcon0MergedSvgUrl + '#unlock',
        'vertical-align-end': iconsIcon0MergedSvgUrl + '#vertical-align-end',
        'vertical-align-middle': iconsIcon0MergedSvgUrl + '#vertical-align-middle',
        'vertical-align-start': iconsIcon0MergedSvgUrl + '#vertical-align-start',
        'warning-triangle': iconsIcon0MergedSvgUrl + '#warning-triangle',
        'zoom-in': iconsIcon0MergedSvgUrl + '#zoom-in',
        'zoom-out': iconsIcon0MergedSvgUrl + '#zoom-out',
    },
    translations: {
        'zh-cn': translationsZhCnJsonUrl,
    },
    embedIcons: {
        codepen: embedIconsCodepenPngUrl,
        codesandbox: embedIconsCodesandboxPngUrl,
        desmos: embedIconsDesmosPngUrl,
        excalidraw: embedIconsExcalidrawPngUrl,
        felt: embedIconsFeltPngUrl,
        figma: embedIconsFigmaPngUrl,
        github_gist: embedIconsGithubGistPngUrl,
        google_calendar: embedIconsGoogleCalendarPngUrl,
        google_maps: embedIconsGoogleMapsPngUrl,
        google_slides: embedIconsGoogleSlidesPngUrl,
        observable: embedIconsObservablePngUrl,
        replit: embedIconsReplitPngUrl,
        scratch: embedIconsScratchPngUrl,
        spotify: embedIconsSpotifyPngUrl,
        tldraw: embedIconsTldrawPngUrl,
        val_town: embedIconsValTownPngUrl,
        vimeo: embedIconsVimeoPngUrl,
        youtube: embedIconsYoutubePngUrl,
    }
}